application: instagram-vrn
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /user
  script: user/index.php

- url: /location
  script: location/index.php

- url: /logout
  script: logout/index.php

- url: /login
  script: login/index.php

- url: /script
  static_dir: script

- url: /style
  static_dir: style

- url: /images
  static_dir: images

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: .*
  script: main.php
