application: instagram-vrn
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /style
  static_dir: style

- url: /images
  static_dir: images

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: .*
  script: main.php
